<?php

namespace App\Application\Sonata\NewsBundle\Document;

use Sonata\NewsBundle\Document\BasePostRepository;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @see https://sonata-project.org/easy-extends
 *
 * References:
 * @see http://www.doctrine-project.org/docs/mongodb_odm/1.0/en/reference/query-builder-api.html
 */
class PostRepository extends BasePostRepository
{
}
