<?php

namespace App\Application\Sonata\MediaBundle\PHPCR;

use Sonata\MediaBundle\PHPCR\BaseGalleryRepository;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @see https://sonata-project.org/easy-extends
 *
 * References :
 * @see http://www.doctrine-project.org/docs/mongodb_odm/1.0/en/reference/query-builder-api.html
 */
class GalleryRepository extends BaseGalleryRepository
{
}
